export const categories = [
    {
        id: 1,
        title: "Work with Shopify POS",
        description: "The Works with Shopify POS feature will allows you to enhance productivity and streamline your workflow",
        image: "/biscuit.jpg",
        appNumber: 104
    },
    {
        id: 2,
        title: "Usefull apps for India",
        description: "The Useful apps for India feature allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/bluetooth.jpg",
    },
    {
        id: 3,
        title: "made-by-shopify ",
        description: "The made-by-shopify feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/juice.jpg",
    },
    {
        id: 4,
        title: "Works with Shopify Marketing",
        description: "The Works with Shopify Marketing feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/chips.jpg",
    },
    {
        id: 5,
        title: "Work with Shopify POS",
        description: "The Works with Shopify POS feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/oil1.jpg",
    },
    {
        id: 6,
        title: "Usefull apps for India",
        description: "The Useful apps for India feature allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/oil2.jpg",
    },
    {
        id: 7,
        title: "made-by-shopify ",
        description: "The made-by-shopify feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/perfume.jpg",
    },
    {
        id: 8,
        title: "Works with Shopify Marketing",
        description: "The Works with Shopify Marketing feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/lakme.jpg",
    },
    {
        id: 9,
        title: "Work with Shopify POS",
        description: "The Works with Shopify POS feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/milk.jpg",
    },
    {
        id: 10,
        title: "Usefull apps for India",
        description: "The Useful apps for India feature allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/camera.jpg",
    },
    {
        id: 11,
        title: "made-by-shopify ",
        description: "The made-by-shopify feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/bluetooth.jpg",
    },
    {
        id: 12,
        title: "Works with Shopify Marketing",
        description: "The Works with Shopify Marketing feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/oil.jpg",
    },
    {
        id: 13,
        title: "Work with Shopify POS",
        description: "The Works with Shopify POS feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/biscuit.jpg",
    },
    {
        id: 14,
        title: "Usefull apps for India",
        description: "The Useful apps for India feature allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/corn.jpg",
    },
    {
        id: 15,
        title: "made-by-shopify ",
        description: "The made-by-shopify feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/juice.jpg",
    },
    {
        id: 16,
        title: "Works with Shopify Marketing",
        description: "The Works with Shopify Marketing feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/chips.jpg",
    },
    {
        id: 17,
        title: "Work with Shopify POS",
        description: "The Works with Shopify POS feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/oil1.jpg",
    },
    {
        id: 18,
        title: "Usefull apps for India",
        description: "The Useful apps for India feature allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/oil2.jpg",
    },
    {
        id: 19,
        title: "made-by-shopify ",
        description: "The made-by-shopify feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/perfume.jpg",
    },
    {
        id: 20,
        title: "Works with Shopify Marketing",
        description: "The Works with Shopify Marketing feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/lakme.jpg",
    },
    {
        id: 21,
        title: "Work with Shopify POS",
        description: "The Works with Shopify POS feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/milk.jpg",
    },
    {
        id: 22,
        title: "Usefull apps for India",
        description: "The Useful apps for India feature allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/camera.jpg",
    },
    {
        id: 23,
        title: "made-by-shopify ",
        description: "The made-by-shopify feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/bluetooth.jpg",
    },
    {
        id: 24,
        title: "Works with Shopify Marketing",
        description: "The Works with Shopify Marketing feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/oil.jpg",
    }, {
        id: 25,
        title: "Work with Shopify POS",
        description: "The Works with Shopify POS feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/biscuit.jpg",
    },
    {
        id: 26,
        title: "Usefull apps for India",
        description: "The Useful apps for India feature allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/corn.jpg",
    },
    {
        id: 27,
        title: "made-by-shopify ",
        description: "The made-by-shopify feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/juice.jpg",
    },
    {
        id: 28,
        title: "Works with Shopify Marketing",
        description: "The Works with Shopify Marketing feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/chips.jpg",
    },
    {
        id: 29,
        title: "Work with Shopify POS",
        description: "The Works with Shopify POS feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/oil1.jpg",
    },
    {
        id: 30,
        title: "Usefull apps for India",
        description: "The Useful apps for India feature allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/oil2.jpg",
    },
    {
        id: 31,
        title: "made-by-shopify ",
        description: "The made-by-shopify feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/perfume.jpg",
    },
    {
        id: 32,
        title: "Works with Shopify Marketing",
        description: "The Works with Shopify Marketing feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/lakme.jpg",
    },
    {
        id: 33,
        title: "Work with Shopify POS",
        description: "The Works with Shopify POS feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/milk.jpg",
    },
    {
        id: 34,
        title: "Usefull apps for India",
        description: "The Useful apps for India feature allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/camera.jpg",
    },
    {
        id: 35,
        title: "made-by-shopify ",
        description: "The made-by-shopify feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/bluetooth.jpg",
    },
    {
        id: 36,
        title: "Works with Shopify Marketing",
        description: "The Works with Shopify Marketing feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/oil.jpg",
    }, {
        id: 37,
        title: "Work with Shopify POS",
        description: "The Works with Shopify POS feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/biscuit.jpg",
    },
    {
        id: 38,
        title: "Usefull apps for India",
        description: "The Useful apps for India feature allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/corn.jpg",
    },
    {
        id: 39,
        title: "made-by-shopify ",
        description: "The made-by-shopify feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/juice.jpg",
    },
    {
        id: 40,
        title: "Works with Shopify Marketing",
        description: "The Works with Shopify Marketing feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/chips.jpg",
    },
    {
        id: 41,
        title: "Work with Shopify POS",
        description: "The Works with Shopify POS feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/oil1.jpg",
    },
    {
        id: 42,
        title: "Usefull apps for India",
        description: "The Useful apps for India feature allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/oil2.jpg",
    },
    {
        id: 43,
        title: "made-by-shopify ",
        description: "The made-by-shopify feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/perfume.jpg",
    },
    {
        id: 44,
        title: "Works with Shopify Marketing",
        description: "The Works with Shopify Marketing feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/lakme.jpg",
    },
    {
        id: 45,
        title: "Work with Shopify POS",
        description: "The Works with Shopify POS feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/milk.jpg",
    },
    {
        id: 46,
        title: "Usefull apps for India",
        description: "The Useful apps for India feature allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/camera.jpg",
    },
    {
        id: 47,
        title: "made-by-shopify ",
        description: "The made-by-shopify feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/bluetooth.jpg",
    },
    {
        id: 48,
        title: "Works with Shopify Marketing",
        description: "The Works with Shopify Marketing feature will allows you to enhance productivity and streamline your workflow",
        appNumber: 104,
        image: "/oil.jpg",
    },
    // Add more categories as needed
];